DROP DATABASE IF EXISTS barbearia;
CREATE DATABASE barbearia CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE barbearia;

CREATE TABLE usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  perfil ENUM('ADMINISTRADOR','RECEPCIONISTA') NOT NULL DEFAULT 'RECEPCIONISTA',
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  ultimo_acesso_em DATETIME NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE barbeiros (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NULL UNIQUE,
  especialidade VARCHAR(150) NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE servicos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome varchar(120) NOT NULL,
    preco double NOT NULL,
    duracao int(2) NOT NULL,
    status tinyint(4) NOT NULL DEFAULT 1
) ENGINE=InnoDB;


-- Usuário inicial: admin@barbearia.com | senha: password
INSERT INTO usuarios (nome, email, senha_hash, perfil) VALUES
('Administrador', 'admin@barbearia.com', '$2y$10$0iJXZ2XYRXcQv200gOn2u.nP4V51CVIlZSC.rayGp3bFlx1.rUToG', 'ADMINISTRADOR');
